-- ============================================================================
-- 04_triggers_scheduler.sql — automation (Databricks SQL / Delta Lake)
--
-- Databricks has NO equivalent of either Oracle feature originally defined
-- in this file:
--   * DML triggers (COMPOUND TRIGGER, AFTER INSERT, etc.) do not exist at
--     all on Delta tables.
--   * DBMS_SCHEDULER jobs are not a SQL concept in Databricks at all —
--     there is no CREATE JOB / CREATE SCHEDULE statement to write here,
--     only the (non-SQL) Databricks Jobs API/UI.
--
-- What changed, construct by construct:
--   trg_qoe_churn_check   -> folded directly into 03_packages.sql's
--                             score_site_qoe_rule_based scripts (both the
--                             single-site and all-sites versions run the
--                             churn-risk UPDATE right after their MERGE
--                             INTO qoe_score — see SECTION 2 there). This
--                             is plain Databricks SQL, no scheduler or
--                             external trigger needed — it runs every time
--                             that script is executed, on demand.
--   JOB_REFRESH_CALL_VOLUME,
--   JOB_RULE_BASED_QOE    -> removed, not recreated. Both existed to keep
--                             feature tables current against a continuous
--                             live CDR/KPI feed; production will instead
--                             get its data from a UI, so there is nothing
--                             to refresh on a schedule. The pipeline runs
--                             against the static CSVs under data/mock/
--                             (scripts/demo_from_csv.py /
--                             scripts/demo_from_sql.py) for now. Re-add a
--                             Databricks Job calling the relevant
--                             03_packages.sql script if/when a live feed
--                             is wired up.
-- ============================================================================

-- No COMMIT needed: Databricks SQL autocommits every DDL/DML statement.
