-- ============================================================================
-- 04_triggers_scheduler.sql — automation (REMOVED)
--
-- This file used to define:
--   TRG_QOE_CHURN_CHECK : a compound trigger that re-checked churn risk
--                         automatically whenever a new QOE_SCORE row was
--                         inserted (called PKG_TRIAGE.flag_churn_risk,
--                         still defined in 03_packages.sql and still used
--                         directly by the batch triage job there).
--   Scheduler jobs      : hourly DBMS_SCHEDULER jobs that refreshed the CDR
--                         aggregate and ran the rule-based QoE fallback
--                         score against live, continuously-arriving data.
--
-- Both were removed: the product will get its data from a UI in production
-- instead of a continuous live feed, so there is nothing to trigger
-- reactively and nothing to refresh on an hourly schedule. For now the
-- pipeline runs against the static CSVs under data/mock/ (see
-- scripts/demo_from_csv.py / scripts/demo_from_sql.py) and churn risk is
-- computed on demand by calling PKG_TRIAGE.flag_churn_risk directly.
-- ============================================================================
